### PR TITLE
Added a requirements.txt and fixed a bug.

### PR DESCRIPTION
**Pull request by pradhan-ritik**
For clarification about the bug, it was about python complaining about a format error in the print f-print statement on line 319 in main.py.
```bash
File "~/coding/contributing/TMS-Pathfinding/main.py", line 319
    f"Walking Time: {floor((distance / 4) // 60)}:{("0" if floor((distance / 4) % 60) < 10 else "") + str(floor((distance / 4) % 60))}")

SyntaxError: f-string: unmatched '('
```
For more details, you can check the commit history.
I also added a requirements.txt.
If you need me to change anything, you can (I enabled edits allowed by maintainers), or you can just tell me to change it.

### CODE REVIEW

**Comment by Pramad712** [comment]
Ok sure

**Comment by Pramad712** [comment]
But one thing I will say though is that I was using Python 3.12 for development, hence why I did not get any errors during my presentation. Should we add 3.12 as a requirement? Or should we do 3.9+ since 3.8 is nearing end-of-life? We can check different versions of python and run the code.

**Comment by pradhan-ritik** [comment]
I think you should have 3.12 as a requirement, since you were using python 3.12 for development.

**Comment by pradhan-ritik** [comment]
Here is the new linux tar btw
[TMS-Pathfinding-Linux.tar.gz](https://github.com/user-attachments/files/16923052/TMS-Pathfinding-Linux.tar.gz)

**Comment by Pramad712** [comment]
Let's update the exes and everything every month and make a new version in the releases page (from now on). Would 9/22 work?

**Comment by pradhan-ritik** [comment]
Okay, that works

**Pull request merged**
